name: flutter_design_patterns
description: Flutter Design Patterns Library

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.0
  font_awesome_flutter: ^10.4.0
  go_router: ^6.2.0
  riverpod_annotation: ^2.0.0
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  xml: ^6.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.3
  lint: ^2.0.1
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/markdown/
    - assets/images/
    - assets/images/abstract_factory/
    - assets/images/adapter/
    - assets/images/bridge/
    - assets/images/builder/
    - assets/images/chain_of_responsibility/
    - assets/images/command/
    - assets/images/composite/
    - assets/images/decorator/
    - assets/images/facade/
    - assets/images/factory_method/
    - assets/images/flyweight/
    - assets/images/interpreter/
    - assets/images/iterator/
    - assets/images/mediator/
    - assets/images/memento/
    - assets/images/observer/
    - assets/images/prototype/
    - assets/images/proxy/
    - assets/images/singleton/
    - assets/images/state/
    - assets/images/strategy/
    - assets/images/template_method/
    - assets/images/visitor/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
